### ISSUE TITLE
define "best"

### ISSUE THREAD

**Issue by ArjixWasTaken** [errias/Kyoku-Cookie-Token-Stealer#23]

**Comment by Sallie-May** [comment]
It is a dualhook. they updated it, i can guess that errias got hacked

**Comment by ArjixWasTaken** [comment]
Why was this closed?
I asked in what way do you have the right to call your filthy program the best.

**Comment by Sallie-May** [comment]
Oooh I though you said like it was the best, you were lkike me after all, saying it's a piece of garbage

**Comment by errias** [comment]
guys.. you are so nerdy

**Comment by Sallie-May** [comment]
and you are  a shit

**Comment by ArjixWasTaken** [comment]
he is shit not only for hiding malware, but for making a token logger

**Comment by Sallie-May** [comment]
The worst part is dualhook, token logger is less worse, still bad but well

**Comment by errias** [comment]
dumbuk9

**Comment by Sallie-May** [comment]
No, still malware

**Comment by ArjixWasTaken** [comment]
> guys.. you are so nerdy

I am a fucking programmer, what else am I supposed to be?

**Comment by AbdullahM0hamed** [comment]
Let's keep all the games

**Comment by AbdullahM0hamed** [comment]
se

**Comment by AbdullahM0hamed** [comment]
a

**Comment by AbdullahM0hamed** [comment]
se

**Comment by AbdullahM0hamed** [comment]
You're welcome @errias

**Comment by Sallie-May** [comment]
Malware Still

**Comment by Sallie-May** [comment]
And the fact that you try to hide the fact that there is a dualhook inside of it is even worse

**Comment by nate-moo** [comment]
Malware
